travel_planner/Accounts/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'Accounts'
urlpatterns =[
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('mypage/', my_page, name='mypage'),
    path('edit_profile/', edit_profile, name='edit_profile'),  # 새로운 URL 패턴 추가
    path('userplan/', user_plan, name='plan'),
    path('userplan/<int:user_plan_id>/', userplan_detail, name='plan_detail'),
    path('plan/delete/<int:plan_id>/', plan_delete, name='plan_delete'),
    path('send_friend_request/', send_friend_request, name='send_friend_request'),  # 수정된 URL 패턴
    path('Myfriends/', my_friends, name='my_friends'),
    path('userplan/<int:plan_id>/edit/', plan_edit, name='plan_edit'),
    path('accept_invite/<int:invite_id>/', accept_invite, name='accept_invite'),
    path('reject_invite/<int:invite_id>/', reject_invite, name='reject_invite'),
    path('my-chats/', my_chat_rooms, name='my_chat_rooms'),
    path('my_reservations/', my_reservation, name='my_reservations'),  # 예약 목록 URL 패턴 추가
    path('my_reservations/<int:reservation_id>/', reservation_detail, name='reservation_detail'),  # 새로운 URL 패턴 추가
    path('my_reservations/delete/<int:reservation_id>/', reservation_delete, name='reservation_delete'),  # 예약 삭제 URL 패턴 추가
    path('my_post/', my_post, name='my_post'),
    path('accept_friend_request/<int:request_id>/', accept_friend_request, name='accept_friend_request'),  # 새로운 URL 패턴 추가
    path('reject_friend_request/<int:request_id>/', reject_friend_request, name='reject_friend_request'),  # 새로운 URL 패턴 추가
    path('delete_friend/<int:friend_id>/', delete_friend, name='delete_friend'),  # 새로운 URL 패턴 추가
    path('reservation/<int:package_id>/', reservation_page, name='reservation_page'),
]

travel_planner/api/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'api'

urlpatterns = [
    path('', homepage_view, name='homepage'),
    path('csrf_token/', get_csrf_token, name='csrf_token'),
    path('flutter_signup/', flutter_signup, name='flutter_signup'),
    path('flutter_login/', flutter_login, name='flutter_login'),
    path('get_user_info/', get_user_info, name='get_user_info'),
    path('flutter_logout/', flutter_logout, name='flutter_logout'),
    path('accommodation/', accommodations_view, name='api_accommodation'),
    path('flutter_plan1/', trip_plan_form, name='flutter_create'),
    path('flutter_plan2/', location, name='flutter_location'),
    path('flutter_plan3/', plan2, name='flutter_accommodation'),
    path('activity/', activity_view, name='fluter_activity'),# 활동 선택
    path('flutter_plan5/<int:trip_plan_id>/', plan4, name='flutter_summary'),
    path('fluter_mypage/', user_info, name='mypage'),
]              # URL 경로 수정

travel_planner/match/urls.py
from django.urls import path
from .views import *

app_name = 'match'
urlpatterns = [
    path('chat/<int:room_id>/', chat_room, name="chat_room"),
    path('create_chat_room/', create_chat_room, name="create_chat_room"),
    path('join_chat_room/<int:room_id>/', join_chat_room, name="join_chat_room"),
    path('', chat_room_list, name="chat_room_list"),
    path('chat/detail/<int:room_id>/', chat_room_detail, name='chat_room_detail'),
    path('delete-chat-room/<int:room_id>/', delete_chat_room, name='delete_chat_room'),
    path('invite_to_trip_plan/', invite_to_trip_plan, name='invite_to_trip_plan'),
    path('change_chat_room_status/<int:room_id>/', change_chat_room_status, name='change_chat_room_status'),

]

travel_planner/travel_planner/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView



urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('Accounts/', include('Accounts.urls')),
    path('planner/', include('planner.urls')),
    path('thesights/', include('thesights.urls')),
    path('hotel/', include('hotel.urls')),
    path('travel/', include('travel.urls')),
    path('chat/', include('match.urls')),
    path('post/', include('post.urls')),
    path('api/', include('api.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

travel_planner/templates/Mypage/Mychat.html
<!DOCTYPE html>
{% include 'Navbar.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>친구</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .mypage{
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        .mypage_content{
            justify-content: center;
            width: 86rem;
            height: 680px;
            margin-top: 50px;
        }

        .page_content{
            float: left;
            margin-right: 0px;
            width: 300px;
            text-align: center;
            font-size: 16px;
        }

        .content_list{
            border-radius: 10px;
            border: 3px solid;
            width: 200px;
            text-align: left;
            font-size: 16px;
            list-style: none;
            margin-top: 40px;
            border-color: #2295ff;
        }

        .content_list>li{
            margin: 25px 0px 25px 70px;
            text-align: center;
            padding-right: 70px;
            color: #2295ff;
        }

        .content_list>hr{
            margin: 0;
            padding: 0;
        }

        .content_name{
            font-size: 26px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .detail_page{
            display: inline-block;
            width: 900px;
            height: 500px;
        }

        #showchat{
            font-weight: bold;
        }

        .content{
            display: flex;
            float: left;
            margin-left: 20px;
        }

        .room_content{
            width: 500px;
            height: 80px;
        }

        .content_title{
            font-weight: bold;
            font-size: 19px;
            margin-bottom: 10px;
        }

        .room_image{
            width: 50px;
            height: 50px;
            border-radius: 50%;
            overflow: hidden;
            border: 1px solid;
            display: inline-block;
            margin-top: 10px;
            margin-left: 10px;
        }

        .room_img{
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .list_content{
            display: inline-block;
            margin-left: 10px;
        }

        .room_name{
            list-style-type: none;
        }

        .room_content{
            border: 1px solid;
            background-color: #D9D9D9;

        }

        .delete_btn{
            background-color: #2295ff;
            color: white;
            border: none;
            font-size: 20px;
            float: right;
            margin: 25px 10px 0px 0px;
        }

        a {
            text-decoration: none;
            color: inherit;
        }


    </style>
</head>
<body>
    <div class="mypage">
        <div class="mypage_content">
            <div class="page_content">
                <ul class="content_list">
                    <li id="showMyInfo"><a href="/Accounts/mypage/">내 정보</a></li><hr>
                    <li id="showLikes">좋아요</li><hr>
                    <li id="showPlans"><a href="/Accounts/userplan/">계획</a></li><hr>
                    <li id="showReservations"><a href="/Accounts/my_reservations">예약</a></li><hr>
                    <li id="showFriends"><a href="/Accounts/Myfriends/">친구</a></li><hr>
                    <li id="showPosts"><a href="/Accounts/my_post/">게시물</a></li><hr>
                    <li id="showchat"><a href="/Accounts/my-chats/">매칭</a></li>
                </ul>
            </div>

            <div class="content_name">
                <p>마이페이지</p>
            </div>

            <div class="detail_page">
                <div class="detail">
                    <div class="chat">
                        <div class="content">
                            <div class="chat_list">
                                <p class="content_title">참여되어 있는 채팅방</p>
                                <ul class="chat_room_list">
                                    {% for room in user_chat_rooms %}
                                        <li class="room_name">
                                            {% if request.user == room.creator %}
                                                <form method="post" action="{% url 'match:delete_chat_room' room.id %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="delete_btn">삭제</button>
                                                </form>
                                                {% endif %}
                                            <div class="room_content">
                                                <div class="room_image">
                                                    <img src="{{ room.image.url }}" alt="" class="room_img">
                                                </div>
                                                <div class="list_content">
                                                    <p class="room_title"><a href="{% url 'match:chat_room_detail' room.id %}">{{ room.name }}</a></p>
                                                    <p class="date">{{ room.date }}</p>
                                                </div>

                                            </div>
                                            
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

travel_planner/templates/Mypage/Myfriend.html
<!DOCTYPE html>
{% include 'Navbar.html'%}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>친구</title>
    <script>
        document.querySelector('form').addEventListener('submit', function(e) {
            e.preventDefault();
            var email = document.querySelector('input[name="email"]').value;
            fetch('/get_user_id_by_email/?email=' + email)
                .then(response => response.json())
                .then(data => {
                    if (data.user_id) {
                        document.getElementById('user_id').value = data.user_id;
                        this.action = "{% url 'Accounts:send_friend_request' %}";
                        this.submit();
                    } else {
                        alert('해당 이메일을 가진 사용자를 찾을 수 없습니다.');
                    }
                });
        });
    </script>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .mypage {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        .mypage_content {
            display: flex;
            justify-content: space-between;
            width: 86rem;
            height: 680px;
            margin-top: 50px;
        }

        .page_content {
            float: left;
            margin-right: 60px;
            width: 300px;
            text-align: center;
            font-size: 16px;
        }

        .content_list {
            border-radius: 10px;
            border: 3px solid;
            width: 200px;
            text-align: left;
            font-size: 16px;
            list-style: none;
            margin-top: 40px;
            border-color: #2295ff;
        }

        .content_list>li {
            margin: 25px 0px 25px 70px;
            text-align: center;
            padding-right: 70px;
            color: #2295ff;
        }

        .content_list>li>a {
            text-decoration: none; /* 밑줄 제거 */
            color: inherit; /* 링크 색상 상속 */
        }

        .content_list>hr {
            margin: 0;
            padding: 0;
        }

        .content_name {
            font-size: 26px;
            font-weight: bold;
            margin-bottom: 50px;
        }

        .detail_page {
            display: flex;
            justify-content: space-between;
            width: 900px;
            height: 500px;
        }

        #showFriends {
            font-weight: bold;
        }

        .friend_list {
            width: 45%;
        }

        .friend_name_list {
            list-style: none;
            padding: 0;
        }

        .friend_name {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .friend_name img {
            width: 50px;
            height: 50px;
            border-radius: 50%;
            object-fit: cover;
            margin-right: 10px;
        }

        .delete_btn {
            color: white;
            background-color: #ff4d4d;
            border: none;
            font-size: 14px;
            padding: 5px 10px;
            cursor: pointer;
        }

        .add_friend {
            width: 45%;
        }

        .add_content {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .add_email {
            margin-bottom: 10px;
        }

        .add_btn {
            color: white;
            background-color: #2295ff;
            border: none;
            font-size: 14px;
            padding: 5px 10px;
            cursor: pointer;
        }

        .request_friend {
            margin-top: 10px; /* 간격 줄이기 */
        }

        .request_friend_item {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .agree_btn, .refuse_btn {
            color: white;
            background-color: #2295ff;
            border: none;
            font-size: 14px;
            margin-left: 10px;
            cursor: pointer;
        }

        .divider {
            border-left: 1px solid #2295ff;
            height: 100%;
            margin: 0 5px; /* 간격 줄이기 */
        }
    </style>
</head>
<body>
    <div class="mypage">
        <div class="mypage_content">
            <div class="page_content">
                <ul class="content_list">
                    <li id="showMyInfo"><a href="/Accounts/mypage/">내 정보</a></li><hr>
                    <li id="showLikes">좋아요</li><hr>
                    <li id="showPlans"><a href="/Accounts/userplan/">계획</a></li><hr>
                    <li id="showReservations"><a href="/Accounts/my_reservations">예약</a></li><hr>
                    <li id="showFriends"><a href="/Accounts/Myfriends/">친구</a></li><hr>
                    <li id="showPosts"><a href="/Accounts/my_post/">게시물</a></li><hr>
                    <li id="showchat"><a href="/Accounts/my-chats/">매칭</a></li>
                </ul>
            </div>

            <div class="detail_page">
                <div class="friend_list">
                    <p class="content_title">친구 목록 ({{ friends.count }}명)</p>
                    <ul class="friend_name_list">
                        {% for friend in friends %}
                        <li class="friend_name">
                            {% if friend.profile_picture %}
                            <img src="{{ friend.profile_picture.url }}" alt="프로필 사진">
                            {% else %}
                            <img src="{% static 'profile_pictures/default.jpg' %}" alt="기본 프로필 사진">
                            {% endif %}
                            {{ friend.username }}
                            <form action="{% url 'Accounts:delete_friend' friend.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="delete_btn">삭제</button>
                            </form>
                        </li>
                        {% empty %}
                        <li>친구가 없습니다.</li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="divider"></div>

                <div class="add_friend">
                    <p class="content_title">친구 관리</p>
                    <div class="add_content">
                        <p>친구 아이디 입력</p>
                        <!-- 친구 추가 -->
                        <form action="{% url 'Accounts:send_friend_request' %}" method="post">
                            {% csrf_token %}
                            <input type="email" name="email" class="add_email" placeholder="친구 e-mail를 입력하세요"><br>
                            <button type="submit" class="add_btn">추가</button>
                        </form>
                    </div>

                    <div class="request_friend">
                        <p class="content_title">친구 요청</p>
                        {% for request in friend_requests %}
                        <div class="request_friend_item">
                            <p>{{ request.from_user.username }}님으로부터 친구 요청이 왔습니다</p>
                            <form action="{% url 'Accounts:accept_friend_request' request.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="agree_btn">수락</button>
                            </form>
                            <form action="{% url 'Accounts:reject_friend_request' request.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="refuse_btn">거절</button>
                            </form>
                        </div>
                        {% empty %}
                        <p>친구 요청이 없습니다.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

travel_planner/templates/Mypage/Myreservations.html
<!DOCTYPE html>
{% include 'Navbar.html'%}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>내 예약 목록</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .mypage{
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        .mypage_content{
            justify-content: center;
            width: 86rem;
            height: 680px;
            margin-top: 50px;
        }

        .page_content{
            float: left;
            margin-right: 60px;
            width: 300px;
            text-align: center;
            font-size: 16px;
        }
        .content_list{
            border-radius: 10px;
            border: 3px solid;
            width: 200px;
            text-align: left;
            font-size: 16px;
            list-style: none;
            margin-top: 40px;
            border-color: #2295ff;
        }

        .content_list>li{
            margin: 25px 0px 25px 70px;
            text-align: center;
            padding-right: 70px;
            color: #2295ff;
        }

        .content_list>hr{
            margin: 0;
            padding: 0;
        }

        .content_name{
            font-size: 26px;
            font-weight: bold;
            margin-bottom: 20px;
        }

        .detail_page{
            display: inline-block;
            width: 900px;
            height: 500px;
        }

        #showReservations{
            font-weight: bold;
        }

        .res_package, .res_lodg, .lodging_title, .package_title{
            border: 1px solid;
            display: inline-block;
            text-align: center;
            width: 100px;
            height: 40px;
            margin: 0px 40px 30px 0px;
            line-height: 40px;
            cursor: pointer;
        }

        .selected_tab {
            background-color: #2295ff;
            color: white;
        }

        .lodg {
            border: 1px solid;
            width: 770px;
            height: 140px;
            display: flex;
            align-items: center;
            margin-right: 10px;
            border: 1px solid #d7d7db;
            margin-bottom: 20px;
            border-radius: 4px;
        }

        .hotel_img {
            width: 300px;
            height: 130px;
            float: left;
            margin: 10px 15px 10px 15px;
            border-radius: 4px;
        }

        .lodg_title {
            font-size: 21px;
            font-weight: bold;
            display: inline-block;
            margin: 0 ;
            margin-top: 10px;
        }

        .lodg_locate {
            margin-top: -20px;
            font-size: 13px;
            color: #8F8F8F;
            text-decoration: underline;
            margin-top: 10px;
        }

        .lodg_star {
            color: #2295FF;
            display: inline-block;
            margin: 5px 5px;
        }

        .lodg_price {
            font-size: 21px;
            font-weight: bold;
            color: #2295FF;
        }

        .fav_icon {
            font-size: 30px;
            cursor: pointer;
            color: #ccc;
            display: flex;
            float: right;
        }

        .fav_icon.fav {
            color: red;
        }      

        .content_sang {
            font-size: 24px;
            color:#2295FF;
            margin-left: 340px;
        }

        a {
            text-decoration: none;
            color: inherit;
        }

        .package_item, .lodging_item {
            border: 1px solid #d7d7db;
            border-radius: 4px;
            margin-bottom: 20px;
            padding: 10px;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .package_item img, .lodging_item img {
            width: 100px;
            height: 100px;
            margin-right: 20px;
            border-radius: 4px;
        }

        .package_title, .lodging_title {
            font-size: 18px;
            font-weight: bold;
        }

        .package_schedule, .package_price, .lodging_schedule, .lodging_price {
            font-size: 16px;
            color: #555;
        }

        .delete-button {
            background-color: #ff4d4d;
            color: white;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
            border-radius: 4px;
        }
    </style>
</head>
<body>
    <div class="mypage">
        <div class="mypage_content">
            <div class="page_content">
                <ul class="content_list">
                     <li id="showMyInfo"><a href="/Accounts/mypage/">내 정보</a></li><hr>
                     <li id="showLikes">좋아요</li><hr>
                     <li id="showPlans"><a href="/Accounts/userplan/">계획</a></li><hr>
                     <li id="showReservations"><a href="/Accounts/my_reservations">예약</a></li><hr>
                     <li id="showFriends"><a href="/Accounts/Myfriends/">친구</a></li><hr>
                     <li id="showPosts"><a href="/Accounts/my_post/">게시물</a></li><hr>
                     <li id="showchat"><a href="/Accounts/my-chats/">매칭</a></li>
                 </ul>
             </div>
            <div class="content_name">
                <p class="content_sang">마이페이지</p>
            </div>

            <div class="detail_page">
                <div class="detail">
                    <div class="reservation">
                        <p class="res_package" onclick="selectTab(this)">패키지 예약</p>
                        <p class="res_lodg" onclick="selectTab(this)">숙소 예약</p>
                        <div id="lodg_info" class="lodging" style="display: none;">
                            {% for reservation in hotel_reservations %}
                                <div class="lodging_item">
                                    <a href="{% url 'Accounts:reservation_detail' reservation.id %}">
                                        <img src="{{ reservation.accommodation.photo.url }}" alt="{{ reservation.accommodation.name }}">
                                        <div>
                                            <p class="lodging_title">{{ reservation.accommodation.name }}</p>
                                            <p class="lodging_schedule">{{ reservation.check_in }} - {{ reservation.check_out }}</p>
                                            <p class="lodging_price">총 가격: {{ reservation.total_price }}원</p>
                                        </div>
                                    </a>
                                    <form method="post" action="{% url 'Accounts:reservation_delete' reservation.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="delete-button">삭제</button>
                                    </form>
                                </div>
                            {% endfor %}
                        </div>
                        <div id="package_info" class="package">
                            {% for reservation in travel_reservations %}
                                <div class="package_item">
                                    <a href="{% url 'Accounts:reservation_detail' reservation.id %}">
                                        <img src="{{ reservation.package.image.url }}" alt="{{ reservation.package.destination }}">
                                        <div>
                                            <p class="package_title">{{ reservation.package.destination }}</p>
                                            <p class="package_schedule">{{ reservation.package.start_date }} - {{ reservation.package.end_date }}</p>
                                            <p class="package_price">총 가격: {{ reservation.total_price }}원</p>
                                        </div>
                                    </a>
                                    <form method="post" action="{% url 'Accounts:reservation_delete' reservation.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="delete-button">삭제</button>
                                    </form>
                                </div>
                            {% endfor %}
                        </div>

                  
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script>    
    window.onload = function() {
        selectTab(document.querySelector('.res_package'));
    };

    function selectTab(element) {
        var tabs = document.querySelectorAll('.res_package, .res_lodg');
        tabs.forEach(function(tab) {
            tab.classList.remove('selected_tab');
        });
        element.classList.add('selected_tab');

        var tabId = element.classList.contains('res_package') ? 'package' : 'lodg';
        showTab(tabId + '_info');
    }

    function showTab(tabId) {
        if (tabId === 'package_info') {
            document.getElementById('package_info').style.display = 'block';
            document.getElementById('lodg_info').style.display = 'none';
        } else {
            document.getElementById('package_info').style.display = 'none';
            document.getElementById('lodg_info').style.display = 'block';
        }
    }
</script>
</html>

travel_planner/templates/Mypage/ReservationDetail.html
<!DOCTYPE html>
{% include 'Navbar.html'%}
{% load humanize %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>예약 상세보기</title>
    <style>
        .reservation-detail {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .reservation-detail h2 {
            margin-bottom: 20px;
        }
        .reservation-detail p {
            margin: 10px 0;
        }
        .accommodation-image {
            width: 100%;
            max-width: 400px;
            height: auto;
            margin-top: 20px;
            border-radius: 4px;
        }
        .traveler-info {
            margin-top: 20px;
        }
        .traveler-info h3 {
            margin-bottom: 10px;
        }
        .traveler-info ul {
            list-style: none;
            padding: 0;
        }
        .traveler-info li {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="reservation-detail">
        <h2>{{ reservation.package.destination }} 예약 상세보기</h2>
        <p><strong>기간:</strong> {{ reservation.package.start_date }} - {{ reservation.package.end_date }}</p>
        <p><strong>숙소:</strong> {{ reservation.package.accommodation.name }}</p>
        <p><strong>인원:</strong> 성인 {{ reservation.adult_count }}명, 청소년 {{ reservation.youth_count }}명, 어린이 {{ reservation.child_count }}명</p>
        <p><strong>총 가격:</strong> {{ reservation.total_price|floatformat:"-0"|intcomma }}원</p>
        <p><strong>예약자 이름:</strong> {{ reservation.user.username }}</p>
        <p><strong>예약자 전화번호:</strong> {{ reservation.user.phone_number }}</p>
        {% if reservation.package.accommodation.photo %}
            <img src="{{ reservation.package.accommodation.photo.url }}" alt="숙소 이미지" class="accommodation-image">
        {% endif %}
        <div class="traveler-info">
            <h3>여행자 명단</h3>
            <ul>
                {% for traveler in reservation.travelers.all %}
                <li><strong>이름:</strong> {{ traveler.name }}, <strong>전화번호:</strong> {{ traveler.phone }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</body>
</html>