travel_planner/Accounts/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'Accounts'
urlpatterns =[
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('mypage/', my_page, name='mypage'),
    path('edit_profile/', edit_profile, name='edit_profile'),  # 새로운 URL 패턴 추가
    path('userplan/', user_plan, name='plan'),
    path('userplan/<int:user_plan_id>/', userplan_detail, name='plan_detail'),
    path('plan/delete/<int:plan_id>/', plan_delete, name='plan_delete'),
    path('send_friend_request/', send_friend_request, name='send_friend_request'),  # 수정된 URL 패턴
    path('Myfriends/', my_friends, name='my_friends'),
    path('userplan/<int:plan_id>/edit/', plan_edit, name='plan_edit'),
    path('accept_invite/<int:invite_id>/', accept_invite, name='accept_invite'),
    path('reject_invite/<int:invite_id>/', reject_invite, name='reject_invite'),
    path('my-chats/', my_chat_rooms, name='my_chat_rooms'),
    path('my_reservations/', my_reservation, name='my_reservations'),  # 예약 목록 URL 패턴 추가
    path('my_reservations/<int:reservation_id>/', reservation_detail, name='reservation_detail'),  # 새로운 URL 패턴 추가
    path('my_reservations/delete/<int:reservation_id>/', reservation_delete, name='reservation_delete'),  # 예약 삭제 URL 패턴 추가
    path('my_post/', my_post, name='my_post'),
    path('accept_friend_request/<int:request_id>/', accept_friend_request, name='accept_friend_request'),  # 새로운 URL 패턴 추가
    path('reject_friend_request/<int:request_id>/', reject_friend_request, name='reject_friend_request'),  # 새로운 URL 패턴 추가
    path('delete_friend/<int:friend_id>/', delete_friend, name='delete_friend'),  # 새로운 URL 패턴 추가
    path('reservation/<int:package_id>/', reservation_page, name='reservation_page'),
]

travel_planner/api/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
app_name = 'api'

urlpatterns = [
    path('', homepage_view, name='homepage'),
    path('csrf_token/', get_csrf_token, name='csrf_token'),
    path('flutter_signup/', flutter_signup, name='flutter_signup'),
    path('flutter_login/', flutter_login, name='flutter_login'),
    path('get_user_info/', get_user_info, name='get_user_info'),
    path('flutter_logout/', flutter_logout, name='flutter_logout'),
    path('accommodation/', accommodations_view, name='api_accommodation'),
    path('flutter_plan1/', trip_plan_form, name='flutter_create'),
    path('flutter_plan2/', location, name='flutter_location'),
    path('flutter_plan3/', plan2, name='flutter_accommodation'),
    path('activity/', activity_view, name='fluter_activity'),# 활동 선택
    path('flutter_plan5/<int:trip_plan_id>/', plan4, name='flutter_summary'),
    path('fluter_mypage/', user_info, name='mypage'),
]              # URL 경로 수정

travel_planner/travel_planner/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView



urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('Accounts/', include('Accounts.urls')),
    path('planner/', include('planner.urls')),
    path('thesights/', include('thesights.urls')),
    path('hotel/', include('hotel.urls')),
    path('travel/', include('travel.urls')),
    path('chat/', include('match.urls')),
    path('post/', include('post.urls')),
    path('api/', include('api.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

travel_planner/Accounts/views.py
import json
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.middleware.csrf import get_token
from .models import CustomUser, Friend, FriendRequest
from planner.models import TripPlan
from hotel.models import HotelReservation
from travel.models import Reservation as TravelReservation
from post.models import Post
from match.models import ChatRoom
from django.views.decorators.csrf import csrf_exempt


def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        age = request.POST.get('age')
        mbti = request.POST.get('mbti')
        gender = request.POST.get('gender')

        # 유효성 검사는 간단한 예시로 하였습니다.
        if username and password and email and age and mbti and gender:
            # 사용자 생성
            user = CustomUser.objects.create_user(
                username=username, password=password, email=email, age=age, mbti=mbti, gender=gender
            )
            messages.success(request, '회원가입이 성공적으로 완료되었습니다.')
            return redirect('/')  # 메인 페이지로 리디렉션
        else:
            messages.error(request, '입력이 올바르지 않습니다. 모든 필드를 채워주세요.')
    return render(request, 'Accounts/signup.html')

def user_login(request):
    if request.method == 'POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'Accounts/login.html')

def logout_view(request):
    logout(request)  # 로그아웃
    return redirect('/')  # 로그아웃 후 리다이렉트할 URL

@login_required
def my_page(request):
    user = request.user
    context = {
        'user': user,
    }
    return render(request, 'Mypage/Myinfo.html', context)

@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        user.age = request.POST.get('age')
        user.mbti = request.POST.get('mbti')
        user.gender = request.POST.get('gender')
        if 'profile_picture' in request.FILES:
            user.profile_picture = request.FILES['profile_picture']
        user.save()
        messages.success(request, '프로필이 성공적으로 업데이트되었습니다.')
        return redirect('/Accounts/mypage/')
    
    context = {
        'user': user,
    }
    return render(request, 'Mypage/EditProfile.html', context)

@login_required
def user_plan(request):
    user = request.user
    user_trip_plans = TripPlan.objects.filter(user=user) | TripPlan.objects.filter(friends=user)

    trip_plan_info = []
    for trip_plan in user_trip_plans.distinct():
        trip_info = {
            'id': trip_plan.id,
            'period': f"기간 : {trip_plan.arrival_date.strftime('%Y.%m.%d')}~{trip_plan.departure_date.strftime('%Y.%m.%d')}",
            'member': f"인원수 : {trip_plan.total_people}명",
            'destination': trip_plan.destination,
            'transportation_method': trip_plan.transportation_method,
            'selected_accommodation': trip_plan.selected_accommodation,
            'selected_activity': trip_plan.selected_activity,
            'friends': list(trip_plan.friends.all())  # 계획에 추가된 친구들을 명시적으로 리스트로 변환
        }
        trip_plan_info.append(trip_info)

    return render(request, 'Mypage/Myplan.html', {'trip_plan_info': trip_plan_info})


@login_required
def userplan_detail(request, user_plan_id):
    user_plan = get_object_or_404(TripPlan, id=user_plan_id)
    friends_list = list(user_plan.friends.all())
    invites = FriendRequest.objects.filter(to_user=request.user, trip_plan=user_plan, status='pending')
    return render(request, 'Detail/plan.html', {'user_plan': user_plan, 'friends': friends_list, 'invites': invites})

@login_required
def plan_delete(request, plan_id):
    plan = get_object_or_404(TripPlan, pk=plan_id)
    if request.method == 'POST':
        plan.delete()
        return redirect('/Accounts/userplan/')
    else:
        return HttpResponse("GET 요청은 허용되지 않습니다.")


@login_required
def plan_edit(request, plan_id):
    user = request.user
    plan = get_object_or_404(TripPlan, pk=plan_id)

    if plan.user != user:
        return HttpResponseForbidden("이 계획을 수정할 권한이 없습니다.")

    try:
        friends = Friend.objects.get(current_user=user).users.all()
    except Friend.DoesNotExist:
        friends = CustomUser.objects.none()

    if request.method == 'POST':
        arrival_date = request.POST.get('arrival_date')
        departure_date = request.POST.get('departure_date')
        total_people = request.POST.get('total_people')
        friend_ids = request.POST.getlist('friends')

        plan.arrival_date = arrival_date
        plan.departure_date = departure_date
        plan.total_people = total_people
        plan.friends.set(friend_ids)
        plan.save()

        for friend_id in friend_ids:
            friend = CustomUser.objects.get(id=friend_id)
            if not FriendRequest.objects.filter(from_user=user, to_user=friend, trip_plan=plan).exists():
                FriendRequest.objects.create(from_user=user, to_user=friend, trip_plan=plan)

        messages.success(request, "계획이 성공적으로 수정되었습니다.")
        return redirect('/Accounts/userplan/')

    return render(request, 'Detail/plan_edit.html', {'user_plan': plan, 'friends': friends})

@login_required
def accept_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id)
    if friend_request.to_user == request.user:
        friend_request.accept()
        messages.success(request, "친구 요청을 수락했습니다.")
    else:
        messages.error(request, "이 친구 요청을 수락할 권한이 없습니다.")
    return redirect('/Accounts/Myfriends/')

@login_required
def reject_friend_request(request, request_id):
    friend_request = get_object_or_404(FriendRequest, id=request_id)
    if friend_request.to_user == request.user:
        friend_request.reject()
        messages.success(request, "친구 요청을 거절했습니다.")
    else:
        messages.error(request, "이 친구 요청을 거절할 권한이 없습니다.")
    return redirect('/Accounts/Myfriends/')

@login_required
def send_friend_request(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        if email:
            try:
                to_user = CustomUser.objects.get(email=email)
                if to_user == request.user:
                    messages.error(request, "자신에게 친구 요청을 보낼 수 없습니다.")
                elif FriendRequest.objects.filter(from_user=request.user, to_user=to_user).exists():
                    messages.warning(request, f"{to_user.username}님에게 이미 친구 요청을 보냈습니다.")
                elif Friend.are_friends(request.user, to_user):
                    messages.info(request, f"{to_user.username}님과 이미 친구입니다.")
                else:
                    friend_request = FriendRequest.objects.create(from_user=request.user, to_user=to_user)
                    notification_message = f"{request.user.username}님으로부터 친구 요청이 왔습니다."
                    friend_request.notification_message = notification_message
                    friend_request.save()
                    messages.success(request, f"{to_user.username}님에게 친구 요청을 보냈습니다.")
            except CustomUser.DoesNotExist:
                messages.error(request, "입력한 이메일 주소를 가진 사용자가 없습니다.")
        else:
            messages.error(request, "유효한 이메일을 입력하세요.")
        return redirect('/Accounts/Myfriends/')
    return render(request, 'Mypage/Myfriend.html')

@login_required
def delete_friend(request, friend_id):
    user = request.user
    friend = get_object_or_404(CustomUser, id=friend_id)
    
    # 친구 관계를 제거합니다.
    Friend.lose_friends(user, friend)
    
    messages.success(request, f"{friend.username}님과의 친구 관계가 삭제되었습니다.")
    return redirect('/Accounts/Myfriends/')

@login_required
def my_friends(request):
    user = request.user
    try:
        friend_relationship = Friend.objects.get(current_user=user)
        friends = friend_relationship.users.all()  # 현재 사용자의 친구 목록
    except Friend.DoesNotExist:
        friends = []

    friend_requests = FriendRequest.objects.filter(to_user=request.user)  # 현재 사용자에게 온 친구 요청 목록

    return render(request, 'Mypage/Myfriend.html', {'friends': friends, 'friend_requests': friend_requests})

@login_required
def my_chat_rooms(request):
    user_chat_rooms = ChatRoom.objects.filter(participants=request.user)
    return render(request, 'Mypage/Mychat.html', {'user_chat_rooms': user_chat_rooms})

@login_required
def my_reservation(request):
    # 현재 로그인한 사용자와 관련된 예약만 가져오기
    hotel_reservations = HotelReservation.objects.filter(user=request.user)
    travel_reservations = TravelReservation.objects.filter(user=request.user)

    # hotel_reservations에서 guests 필드 사용
    for reservation in hotel_reservations:
        reservation.total_guests = reservation.guests

    # travel_reservations에서 adult_count, youth_count, child_count 필드 사용
    for reservation in travel_reservations:
        reservation.total_guests = (
            reservation.adult_count + 
            reservation.youth_count + 
            reservation.child_count
        )

    return render(request, 'Mypage/Myreservations.html', {
        'hotel_reservations': hotel_reservations,
        'travel_reservations': travel_reservations
    })

@login_required
def reservation_detail(request, reservation_id):
    try:
        reservation = TravelReservation.objects.get(id=reservation_id)
    except TravelReservation.DoesNotExist:
        raise Http404("해당 예약을 찾을 수 없습니다.")
    return render(request, 'Mypage/ReservationDetail.html', {'reservation': reservation})

travel_planner/templates/Accounts/login.html
{% include 'AccountNavbar.html'%}
<html>
    <title>로그인 - Travel Plan</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .login_page {
            display: flex;
            justify-content: center;
        }

        .page_title{
            text-align: center;
            font-weight: bold;
            font-size: 30px;
        }

        .login_input{
            text-align: center;
            margin-top: 2cap;
        }

        .input_text{
            width: 300px;
            height: 40px;
            margin-bottom: 10px;
            border-radius: 5px;
            border-color: #949494;
            border-style: solid;
            border-width: 1px;
        }

        .black_btn {
            border: none;
            background-color: #2295ff;
            color: white;
            width: 300px;
            height: 45px;
            margin: 10px;
            border-radius: 5px;
        }

        .signup_btn {
            background-color: white;
            color: #2295ff;
            width: 300px;
            height: 45px;
            margin: 10px;
            border-radius: 5px;
            border-color: #2295ff;
            box-shadow: none !important; /* 그림자 완전히 제거 */
            border: 2px solid #2295ff;   /* 테두리를 명시적으로 설정 */
            box-shadow: none;
        }

        .black_btn {
            font-size: 16px;
            font-weight: bold;
        }

        .signup_btn {
            font-size: 16px;
            font-weight: bold;
        }

        .signup_btn >a {
            color: inherit;
            text-decoration: none;
        }
    </style>

<form method="post"  class="login_page" action="{% url 'Accounts:login' %}">
    {% csrf_token %}
    <div class="login_content">
        <p class="page_title">로그인</p>
        <div class="login_input">
            <input class="input_text" type="text" name="username" title="아이디 입력" placeholder="아이디" value="{{ form.username.value|default_if_none:''}}"   ><br>
            <input class="input_text" type="password" name="password" title="비밀번호" placeholder="비밀번호" value="{{ form.password.value|default_if_none:'' }}">

            <div class="login_btn">
                <button class="black_btn"> 로그인</button>
            </div>
            <button class="signup_btn"><a href="/Accounts/signup/">회원가입</a></button>
        </div>
    </div>
</body>
</form>

</html>

travel_planner/templates/Accounts/my_reservations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Reservations</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
            text-align: left;
        }
        img {
            max-width: 100px;
            height: auto;
        }
    </style>
</head>
<body>
    <h1>My Reservations</h1>
    <table>
        <thead>
            <tr>
                <th>Image</th>
                <th>Package</th>
                <th>Destination</th>
                <th>Adults</th>
                <th>Youths</th>
                <th>Children</th>
                <th>Total Price</th>
                <th>Reserved At</th>
            </tr>
        </thead>
        <tbody>
            {% for reservation in reservations %}
            <tr>
                <td><img src="{{ reservation.package.image.url }}" alt="Package Image"></td>
                <td>{{ reservation.package.destination }}</td>
                <td>{{ reservation.package.destination }}</td>
                <td>{{ reservation.adult_count }}</td>
                <td>{{ reservation.youth_count }}</td>
                <td>{{ reservation.child_count }}</td>
                <td>{{ reservation.total_price }}</td>
                <td>{{ reservation.created_at }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

travel_planner/templates/Accounts/signup.html
<!DOCTYPE html>
{% include 'AccountNavbar.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입 - Travel Plan</title>
    <style>
         * {
            margin: 0;
            padding: 0;
        }

        .signup_page {
            display: flex;
            justify-content: center;
        }

         .page_title{
            text-align: center;
            margin-bottom: 20px;
            font-size: 30px;
        }
        .signup_input{
            width:300px;
        }

        .input_name{
            font-size: 18px;
            font-weight: bold;
        }

        .input_text{
            width:300px;
            height:30px;
            font-size: 16px;
            border-radius: 5px;
            border-color: #949494;
            border-style: solid;
            border-width: 1px;
        }

        .select_gender{
            width: 300px;
            height: 35px;
            font-size: 16px;
            border-radius: 5px;
            border-color: #949494;
            border-style: solid;
            border-width: 1px;
        }

        .select_gender>option{
            font-size: 16px;
        }

        .submit_btn{
            border: none;
            background-color: #2295ff;
            color: white;
            text-align: center;
            display: block;
            margin: 0 auto;
            margin-top: 20px;
            font-size: 16px;
            font-weight: bold;
            border: none;
            width: 300px;
            height: 45px;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <form class="signup_page" method="post" action="{% url 'Accounts:signup' %}">
        {% csrf_token %}
        <div class="signup_content">
            <h2 class="page_title">회원가입</h2>

            <div class="signup_input">
                <label class="input_name" for="username">사용자 이름</label><br>
                <input class="input_text" type="text" id="username" name="username"><br>
                <label class="input_name" for="password">비밀번호</label><br>
                <input class="input_text" type="password" id="password" name="password"><br>
                <label class="input_name" for="email">이메일</label><br>
                <input class="input_text" type="email" id="email" name="email"><br>
                <label class="input_name" for="age">나이</label><br>
                <input class="input_text" type="number" id="age" name="age"><br>
                <label class="input_name" for="mbti">MBTI</label><br>
                <input class="input_text" type="text" id="mbti" name="mbti"><br>
                <label class="input_name" for="gender">성별</label><br>
                <select id="gender" name="gender" class="select_gender">
                    <option value="male">남자</option>
                    <option value="female">여자</option>
                </select><br>
                <button class="submit_btn" type="submit">가입하기</button>
            </div>
        </div>

    </form>
</body>
</html>